[package]
name = "gussing_games"
version = "0.1.0"
authors = ["Chineseguuys <yanjianghan1996@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
